image: maven:3.3.9-jdk-8

stages:
- validate
- build
- review

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - /root/.m2/repository/
    - .m2/repository/
    - target/

validate:
  stage: validate
  script:
    - 'mvn validate'

build:
  stage: build
  script:
    - 'mvn clean install'
  artifacts:
    expire_in: 1 week
    paths:
      - target/*.jar

codacy:
  stage: review
  script:
  - curl https://api.codacy.com/events/push/c5be80fef8484d9b95387cda224e6fd8
