# HIKARICP konfigurace
# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Trvale smazani entit (ArmorStandu ve svetech)
fix-armorstands: false

# Player counter
player-count: 0

# Block fix data
block-fix:
 cooldown-checker: 50
 cooldown-checker-removal: 1250
 update-interval: 5
 radius: 4