# HIKARICP konfigurace
# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Trvale smazani entit (ArmorStandu ve svetech)
fix-armorstands: false

# Player counter
player-count: 0

# Debug
debug: false

# Drop protector
protect-drop:
 - DIAMOND_PICKAXE