name: CraftPrison
main: cz.wake.craftprison.Main
authors: [MrWakeCZ]
depend: [Multiverse-Core,CraftCore,Vault]
softdepend: [AutoSell, VKBackPack]
version: 1.0

commands:
    rank:
      description: Zakladni prikaz
    rankup:
      description: No..
    test:
      description: Na testy