name: CraftPrison
main: cz.wake.craftprison.Main
authors: [MrWakeCZ]
depend: [Multiverse-Core,CraftCore,Vault]
softdepend: [AutoSell,VKBackPack,MVdWPlaceholderAPI]
version: 1.0

commands:
    rank:
      description: Zakladni prikaz
    rankup:
      description: No..
    stats:
      description: Statistiky
    pcoins:
      description: PrisCoiny
      aliases: [pc, pcoin]
    pickaxe:
      description: Pickaxe upgrade system
      aliases: [krumpac, krump]
    tutorial:
      description: Napoveda k Prisonu
      aliases: [help]
    pvp:
      description: Teleport do pvp
    mine:
      description: Prikaz na primy teleport do dolu
      aliases: [dul]
    ranks:
      description: Prikaz na zobrazeni ranku
    pshop:
      description: Exp shop za PrisCoiny
    prodat:
      description: Proda vsechny bloky v danem ranku
      aliases: [prodej, vykup]